env:
  - DB=postgresql

before_install:
  - gem install bundler
  - bundle install
  - psql -c 'create database db_test' -U postgres
  - bundle exec rake db:migrate --trace

# whitelist
branches:
  only:
    - /^.*$/

language: ruby
rvm:
  - 2.0.0-p0

addons:
  code_climate:
    repo_token: 74f7f5459765526873d8d30de486ca2ca62c6968410049437fd3429419dbd7c2

script: bundle exec rspec spec